# referenced  https://github.com/junjiehe96/FastInst/blob/main/configs/coco/instance-segmentation/Fast-COCO-InstanceSegmentation.yaml
MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: [ "res3", "res4", "res5" ]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [ 1, 1, 1 ]  # not used
  FASTINST:
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
  # quoted from https://github.com/zhang-tao-whu/DVIS/blob/main/configs/ovis/Base-OVIS-VideoInstanceSegmentation.yaml
  MASK_FORMER:
    TEST:
      WINDOW_SIZE: 3
      WINDOW_INFERENCE: True
      TASK: 'vis'

# quoted from https://github.com/aimedical/clearml-dvis-scc/blob/main/DVIS/configs/scc/Base-OVIS-VideoInstanceSegmentation.yaml
DATASETS:
  DATASET_RATIO: [1.0, ]
  DATASET_NEED_MAP: [False, ]
  DATASET_TYPE: ['video_instance', ]
  DATASET_TYPE_TEST: ['video_instance', ]
  # The categories of all datasets will be mapped to the categories of the last dataset
  TRAIN: ("scc_train",)
  TEST: ("scc_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  STEPS: (7000,)
  MAX_ITER: 10000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  RANDOM_FLIP: "flip_by_clip"
  AUGMENTATIONS: []
  MIN_SIZE_TRAIN: (360, 480)
  MIN_SIZE_TEST: 360
  CROP:
    ENABLED: False
    TYPE: "absolute_range"
    SIZE: (600, 720)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 0
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
VERSION: 2