# referenced https://github.com/zhang-tao-whu/DVIS/blob/main/configs/ovis/MinVIS_R50.yaml
_BASE_: Base-SCC-VideoInstanceSegmentation.yaml
MODEL:
  WEIGHTS: "/workspace/model/fastinst_R50_ppm-fpn_x3_640_37.9.pth"
  META_ARCHITECTURE: "MinVIS"
  SEM_SEG_HEAD:
    NAME: "FastInstHead"
    IGNORE_VALUE: 9
    NUM_CLASSES: 9
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "PyramidPoolingModuleFPN"
    IN_FEATURES: [ "res3", "res4", "res5" ]
  FASTINST:
    TRANSFORMER_DECODER_NAME: "VideoFastInstDecoder_dvis"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    LOCATION_WEIGHT: 1000.0
    PROPOSAL_WEIGHT: 20.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NUM_AUX_QUERIES: 8
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 1024
    PRE_NORM: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 3
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8

# quoted from https://github.com/aimedical/clearml-dvis-scc/blob/main/DVIS/configs/scc/MinVIS_R50.yaml
SOLVER:
  IMS_PER_BATCH: 24
  BASE_LR: 0.0001
  STEPS: (14000,)
  MAX_ITER: 100
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05

INPUT:
  MIN_SIZE_TRAIN: (240, 360, 480)
  MAX_SIZE_TRAIN: 768
  MIN_SIZE_TEST: 360
  SAMPLING_FRAME_NUM: 1

  SAMPLING_FRAME_SHUFFLE: False
  # MIN_SIZE_TRAIN_SAMPLING : ["range", "choice", "range_by_clip", "choice_by_clip"]
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  # RANDOM_FLIP : ["none", "horizontal", "flip_by_clip"]. "horizontal" is set by default.
  RANDOM_FLIP: "flip_by_clip"
  AUGMENTATIONS: []
  CROP:
    ENABLED: False
    TYPE: "absolute_range"
    SIZE: (384, 600)
  # For pseudo videos
  PSEUDO:
    AUGMENTATIONS: ['rotation']
    MIN_SIZE_TRAIN: (240, 360, 480)
    MAX_SIZE_TRAIN: 768
    CROP:
      ENABLED: False
      TYPE: "absolute_range"
      SIZE: (384, 600)
  LSJ_AUG:
    ENABLED: False
    IMAGE_SIZE: 768
    MIN_SCALE: 0.1
    MAX_SCALE: 2.0

DATASETS:
  DATASET_RATIO: [1.0, ]
  DATASET_NEED_MAP: [False, ]
  DATASET_TYPE: ['video_instance', ]
  DATASET_TYPE_TEST: ['video_instance', ]
  # The categories of all datasets will be mapped to the categories of the last dataset
  TRAIN: ("scc_9cls_train", )
  TEST: ("scc_9cls_val",)

OUTPUT_DIR: './output_MinVIS_R50_SCC'